mindsdb_infra:
  host: 127.0.0.1
  port: 47334

knowledge_base:
  name: arxiv_kb
  embedding_model: text-embedding-3-small
  reranking_model: gpt-4o
  metadata_columns:
    - authors
    - categories
    - published_year
    - primary_category
    - article_id
    - title
    - abstract
  storage:
    enable_pg_vector: False
    pg_vector_database: pgvec_db
    pg_vector_table: vec_table
  content_columns:
    - text

postgres:
  host: localhost
  port: 5432
  database: arxiv_psql_db
  user: postgres
  password: postgres
  table_name: arxiv_txt

agent:
  openai_model: gpt-4o

app:
  log_level: INFO
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  load_sample_data: True
  sample_data_count: 5
  openai_api_key: <sk-proj>

