mindsdb_infra:
  host: 127.0.0.1
  port: 47334

knowledge_base:
  name: test_kb
  embedding_model: text-embedding-3-small
  reranking_model: gpt-4o
  openai_api_key: <sk-proj>
  metadata_columns:
    - authors
    - categories
    - published_year
    - primary_category
    - article_id
    - title
    - summary
  storage:
    enable_pg_vector: True
    pg_vector_database: pgvec_db
    pg_vector_table: vec_table
  content_columns:
    - text

postgres:
  host: localhost
  port: 5432
  database: arxiv_psql_db
  user: postgres
  password: postgres
  table_name: arxiv_txt

agent:
  openai_model: gpt-4o

app:
  log_level: INFO
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  load_sample_data: True
  sample_data_count: 2

benchmark:
  batch_sizes: [10, 20]
  test_data_path: /home/abhi/refactored/data/data.json
  queries_file_path: /home/abhi/refactored/data/queries.json
  baseline_metrics_path: ""
  output_dir: test_reports
  iterations: 1

stress:
  batch_size: 50
  test_data_path: /home/abhi/refactored/data/data.json
  queries_file_path: /home/abhi/refactored/data/queries.json
  baseline_metrics_path: ""
  output_dir: test_reports
  concurrent_users: [1, 2, 3]
  max_concurrent_users: 5
  max_data_size: 10
  data_sizes: [3, 6, 9]
